name: Render and deploy GitBook
'on':
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    container: rocker/verse
    steps:
      - name: Build GitBook
        run: |-
          Rscript -e "bookdown::render_book('index.Rmd', 'all', output_dir = 'docs')"
